language: php

php:
  - 5.6
  - 7.0

before_script:
  - cd app
  - cp .env.example .env
  - php artisan key:generate
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit